Repository WebisD/http-api-without-lib, pull requests merged in 2021-04, with the labels that each got.

#1 Feat create request message parser
  Handler/handlerRequests.py
  Handler/requestParser.py
  server.py
Labels: enhancement

#10 Feat create get method and fix post not rendering
  assets/bootstrap-4.0.0/favicon.svg
  assets/bootstrap.css.map
  assets/bootstrap.min.css
  assets/bootstrap.min.css.map
  assets/bootstrap.min.js
  assets/bootstrap.min.js.map
  assets/error.html
  assets/index.html
  assets/list.html
  assets/popper.min.js
  assets/post.html
  databaseUser/ObjectUser.py
  databaseUser/database.json
  handler/HandlerErrors.py
  main.py
  message/Request.py
  message/Response.py
  methods/DELETE.py
  methods/GET.py
  methods/POST.py
  methods/PUT.py
  server.py
Labels: bug, enhancement

#16 Feat Error page and translated to english
  assets/error.html
  assets/index.html
  assets/list.html
  assets/post.html
  assets/static/error.gif
  databaseUser/database.json
  handler/HandlerErrors.py
  handler/HandlerRequests.py
  message/StatusCode.py
  methods/DELETE.py
  methods/GET.py
Labels: enhancement, good first issue

#18 Fix bugs in multiple requests and add colored buttons for different responses
  assets/bootstrap.min.css
  assets/post.html
  assets/put.html
  databaseUser/HandlerDatabase.py
  methods/POST.py
  methods/PUT.py
  server.py
Labels: bug, enhancement
